version: "3.8"

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lesson-plan
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports: 
      - 5432:5432 