version: "3.8"

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lesson-plan
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432 
