version: "3.8"

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lesson-plan
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports: 
      - 5434:5432
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug', '--import-realm']
    ports:
      - 8080:8080
      - 8443:8443
      - 8686:8787
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
  backend:
    container_name: backend
    image: 'vanessanicole/lesson-plan-backend'
    restart: always
    environment:
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - FRONTEND=${FRONTEND-URL}
      - ENV=${ENV}
      - PORT_LISTEN=${PORT_LISTEN}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - AUTH_SERVICE_TENANT=${AUTH_SERVICE_TENANT}
    ports:
      - 4008:4008
