export enum RemedialPlanSteps {
    CREATED = 1,
    SIGNED_BY_TEACHER = 2,
    SENT_TO_MANAGER = 3,
    VALIDATED_BY_MANAGER = 4,
    SIGNED_BY_MANAGER = 5,
    SENT_TO_TEACHER_STUDENTS = 6,
    ACCEPTED_BY_STUDENTS = 7,
    SENT_TO_MANAGER_AND_TEACHER = 8,
    FINISHED = 9,
  }
  