export enum RemedialLessonPlanSteps {
  CREATED = 1,
  SIGNED_BY_TEACHER = 2,
  SENDED_TO_MANAGER = 3,
  VALIDATED_BY_MANAGER = 4,
  SIGNED_BY_MANAGER = 5,
  SENDED_TO_STUDENTS_AND_TEACHER = 6,
  ACCEPTED_BY_STUDENTS = 7,
  REPORT_SENDED_TO_MANAGER_AND_TEACHER = 8,
  FINISHED = 9
}
